#ifndef __MULTI_PRIVATE_H__
#define __MULTI_PRIVATE_H__

//#define DEBUG_MODE_FPGA_CONFIG_ONCE

//#define DEBUG_CARD_PLATFORM_CHN_IO_STAT

//#define DEBUG_MODE_INIT_BUNNER_MODE

//#define SUPPORT_HWL_FPGA_REG_MODULE

//#define SUPPORT_PES_ANALYS_FUNCTION

//#define CARD_TEST

//#define DEBUG_SPI_FLASH_INTERFACE

//#define DEBUG_DISABLE_FRP//测试用，主要是释放前面板的串口用作其它用途

//#define DEBUG_SHOW_PIDMAP

//#define DEBUG_IP_TO_TS_PROTOCOL//调试FPGA TUN接口

#define MULT_EMM_REPLICATE_MODE

//#define KERNEL_AUTO_UPDATE

//#define REQUEST_2014_0110_ONLY_GOS_CA//巴基斯坦装怪需求，使得CA只连接本公司的

//#define SUPPORT_2730_IP_BOARD_4CE55_SUPPORT

/*授权测试*/
//#define MULT_LICENSE_DEBUG	
//#define MULT_TS_BACKUP_SUPPORT
//#define MULT_UNUSED_TS_DISABLE_SUPPORT


//#define USE_TD_MODULE	//调试TUNER / DEMOD		


//#define SUPPORT_SFN_MODULATOR

//#define SUPPORT_SFN_ADAPTER

//#define SUPPORT_DTMB_REMOTE_PROTOCOL

//#define USE_NEW_QAM_SETTING_FUNCTIONS

//#define SUPPORT_IP_O_TS_MODULE

//#define SUPPORT_GNS_MODULE //GPS/BDS 系统支持控制

//#define SUPPORT_VRS232_MODULE//FPGA 虚拟RS232接口


//#define SUPPORT_CLK_ADJ_MODULE//FPGA 10M调整模块

//#define SUPPORT_FGPIO_MODULE// FPGA GPIO 功能

//#define SUPPORT_MODULATOR_FPGA_TONE

//#define SUPPORT_MODULATOR_FREQ_1_HZ

//#define SUPPORT_MODULATOR_FREQ_ACCURACY

//#define SUPPORT_BSS_SCRAMBLE_SYSTEM

//#define DISABLE_REMUX_MODULE		//关闭复用模块，但是节目可以搜索

//#define DISABLE_ROUTE_MODULE		//无法对Route进行操作

//#define SUPPORT_REMOTE_COM_CONTROL


//#define SUPPORT_FIR_II_RELOAD

#define SUPPORT_LOCAL_ENCODER_APP

#define SUPPORT_LOCAL_ENCODER_HWL

//#define DEBUG_MODULATOR

//#define USE_MAX287X_2200_40M
//#define USE_MAX287X_2200_10M
//#define USE_MAX287X_2400_40M
//#define USE_MAX287X_2400_10M

//#define SUPPORT_NTS_DPD_BOARD//芯通的DPD调制板控制模块
//#define SUPPORT_NEW_FRP_MENU_MODULE
//#define USE_NEW_QAM_SETTING_FUNCTIONS

#define MULT_LICENSE_DEBUG_MARK_VALID					( TRUE )
#define MULT_LICENSE_DEBUG_MODE							( 1 )
#define MULT_LICENSE_DEBUG_OUT_TS_NUM					( 1 )
#define MULT_LICENSE_DEBUG_ASI_TS_NUM					( 4 )
#define MULT_LICENSE_DEBUG_SCS_NUM						( 3 )
#define MULT_LICENSE_DEBUG_SCRAMBLE						( TRUE )

#define MULT_IP_CHN_DEFAULT_BITRATE						(950 * 1000000)
#define MULT_IP_SUB_DEFAULT_OUTPUT_BITRATE				(200 * 1000000)
#define MULT_IP_CHN_MAX_BITRATE							(970 * 1000000)

#define MULT_ASI_MAX_BITRATE							(216 * 1000000)
#define MULT_ASI_MAX_OUTPUT_BITRATE						(100 * 1000000)
#define MULT_ASI_DEFAULT_OUTPUT_BITRATE					(70 * 1000000)

#define MULT_SYSTEM_ENABLE_AUTO_MAP_FUNCTION			0

//#define MULT_SERVICE_MAX_NUM							(512)


#if defined(GQ3710A)
#define MULTL_PLL_STAND_VALUE				(67.5*1000*1000 / 2)
#define MULTL_PLL_OFFSET_LIMIT				(7000000)
#define MULTL_PLL_ERROR_TORLARANCE			(16)
#elif defined(GQ3760A) || defined(LR1800S) || defined(GQ3763) || defined(GQ3760) || defined(GQ3768) || defined(GQ3765)
#define MULTL_PLL_STAND_VALUE				(7560000/2)
#define MULTL_PLL_OFFSET_LIMIT				(100)
#define MULTL_PLL_ERROR_TORLARANCE			(16)
#elif defined(GQ3760B)
#define MULTL_PLL_STAND_VALUE				(7560000)
#define MULTL_PLL_OFFSET_LIMIT				(100)
#define MULTL_PLL_ERROR_TORLARANCE			(16)
#else
#define MULTL_PLL_STAND_VALUE				(67.5*1000*1000 / 4)
#define MULTL_PLL_OFFSET_LIMIT				(7000000)
#define MULTL_PLL_ERROR_TORLARANCE			(16)
#endif

#ifdef GQ3650DR

#define MULT_DEVICE_TYPE							0x27
#define MULT_DEVICE_SUB_TYPE				        0x19

#define MULT_SOFT_VERSION							"01.08"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3650DR"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"Multifunctional QAM Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"多功能调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"Multi QAM Modulator"
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    多功能调制器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3650DR.rbf"
#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3650DR
#define MULT_DEVICE_MODUATION_NUM					(4)

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048

#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_FPGA_MAIN_CLK							(62.5)

//#define SUPPORT_SYSLOG_MODULE
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION

#define SUPPORT_BSS_SCRAMBLE_SYSTEM
#define MULT_SERVICE_MAX_NUM							(256)

#endif



#ifdef GQ3650DS

#define MULT_DEVICE_TYPE							0x73
#define MULT_DEVICE_SUB_TYPE				        0x84

#define MULT_SOFT_VERSION							"01.29"
#define MULT_HARD_VERSION							"01.10"
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3650DS"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"Multifunctional QAM Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"多功能调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"Multi QAM Modulator"
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    多功能调制器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3650DS.rbf"

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3650DS						
#define MULT_DEVICE_MODUATION_NUM					(4)

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x00
#define MULT_DEVICE_E3_DS3_NUM						0x04
#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
//#define SUPPORT_SYSLOG_MODULE
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
#define SUPPORT_BSS_SCRAMBLE_SYSTEM
#define MULT_SERVICE_MAX_NUM							(256)

#endif



#ifdef GQ3710A

#define MULT_DEVICE_TYPE							0x27
#define MULT_DEVICE_SUB_TYPE				        0x36

#define MULT_SOFT_VERSION							"01.03"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3710A"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"QPSK Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"QPSK  调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"   QPSK Modulator   "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    QPSK  调制器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3710A.rbf"

#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3710A	

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
#define SUPPORT_BSS_SCRAMBLE_SYSTEM
#define MULT_SERVICE_MAX_NUM							(256)

#endif




#ifdef GA2620B

#define MULT_DEVICE_TYPE							0x27
#define MULT_DEVICE_SUB_TYPE						0x24

#define MULT_SOFT_VERSION							"01.10"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GA-2620B"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"DVB TS Scrambler"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"DVB TS 加扰机"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"  DVB TS Scrambler  "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"   DVB TS 加扰机    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/FPGA2730S_2620.rbf"

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2620B				

#define MULT_DEVICE_TUNER_NUM						0x00
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_DEVICE_MODUATION_NUM					(0)

#define MULT_DEVICE_OLD_HW_INFO_AND_HEAR_BEAT		
#define MULT_DEVICE_NO_TEMP_SENSOR		
#define MULT_USE_ALTERNATE_FPGA_CONFIG

#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			0
#define MULT_FPGA_MAIN_CLK							(75)
#define SUPPORT_BSS_SCRAMBLE_SYSTEM
#define MULT_SERVICE_MAX_NUM							(256)

#endif

# if defined(GM2700B) || defined(GM2700S)

#define MULT_DEVICE_TYPE							0x27

#ifdef GM2700S
#define MULT_DEVICE_SUB_TYPE				        0x39
#else
#define MULT_DEVICE_SUB_TYPE				        0x38
#endif


#ifdef GM2700S
#define MULT_DEFAULT_DEVICE_MODEL					"GM-2700S"
#define MULT_SOFT_VERSION							"10.03"
#define MULT_HARD_VERSION							"02.00"
#else
#define MULT_DEFAULT_DEVICE_MODEL					"GM-2700B"
#define MULT_SOFT_VERSION							"10.00"
#define MULT_HARD_VERSION							"02.00"
#endif

#define MULT_DEFAULT_DEVICE_NAME_ENG				"TS ReMultiplexer"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"TS 复用器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"  TS ReMultiplexer "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"     TS 复用器      "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/FPGA2730S_2620.rbf"

#define MULT_DEVICE_MODUATION_NUM					(0)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2700X		

#define MULT_DEVICE_TUNER_NUM						0x00
#define MULT_DEVICE_E3_DS3_NUM						0x00


#define MULT_DEVICE_FPGA_CONFIG_IN_AS_MODE
#define MULT_DEVICE_NOT_SUPPORT_ENCRYPT_CHIP
#define MULT_SN_FILE_NAME							"/mnt/mtd/device.sn"
#define MULT_DEVICE_OLD_HW_INFO_AND_HEAR_BEAT		
#define MULT_DEVICE_NO_TEMP_SENSOR		

#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			0
#define MULT_FPGA_MAIN_CLK							(75)
#define SUPPORT_BSS_SCRAMBLE_SYSTEM
#define MULT_SERVICE_MAX_NUM							(256)

#endif



#ifdef GM2730X
//V01.03 增加4CE55支持，同时界面变化和1772相同！
//特殊字设备GM2762，输出PAT PID 修改为0x1000 SDT PID修改为0x1011的特殊版本
//#define GM2762
/*IP <-> ASI*/

#define MULT_SOFT_VERSION							"01.03"
#define MULT_HARD_VERSION							"01.00"
#define MULT_HARD_VERSION_4CE55						"01.10"

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/FPGA2730S_2730X.rbf"
#define HWL_CONST_FPGA_FILE_PATH_4CE55				"/tmp/FPGA2730S_2730X_4CE55.rbf"

#define MULT_DEVICE_TYPE							(0x27)
#define MULT_DEVICE_SUB_TYPE						(0x15)

#define MULT_DEFAULT_DEVICE_MODEL					"GM-2730X"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"IP - ASI Adaptor"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"IP - ASI 适配器"

#define MULT_DEFAULT_DEVICE_LCD_ENG					"  IP - ASI Adaptor  "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"  IP - ASI  适配器  "



#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2730X		

#define MULT_DEVICE_MODUATION_NUM					(0)
#define MULT_DEVICE_ASI_IN_NUM						(0x04)
#define MULT_DEVICE_ASI_OUT_NUM						(0x04)
#define MULT_DEVICE_TUNER_NUM						(0x00)
#define MULT_DEVICE_E3_DS3_NUM						(0x00)
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			(2048)
#define MULT_FPGA_MAIN_CLK							(62.5)

#define MULT_DEVICE_OLD_HW_INFO_AND_HEAR_BEAT		
#define MULT_DEVICE_NO_TEMP_SENSOR		
#define MULT_USE_ALTERNATE_FPGA_CONFIG
#define SUPPORT_NEW_ALARM_SYSTEM
#define SUPPORT_BSS_SCRAMBLE_SYSTEM

#define SUPPORT_2730_IP_BOARD_4CE55_SUPPORT

#ifdef GM2762
#undef MULT_SOFT_VERSION
#define MULT_SOFT_VERSION							"01.00"

#undef MULT_DEVICE_TYPE
#define MULT_DEVICE_TYPE							(0x27)
#undef MULT_DEVICE_SUB_TYPE
#define MULT_DEVICE_SUB_TYPE						(0x15)

#undef MULT_DEFAULT_DEVICE_MODEL
#define MULT_DEFAULT_DEVICE_MODEL					"GM-2762"
#undef MULT_DEFAULT_DEVICE_NAME_ENG
#define MULT_DEFAULT_DEVICE_NAME_ENG				"IP Remux"
#undef MULT_DEFAULT_DEVICE_NAME_CHN
#define MULT_DEFAULT_DEVICE_NAME_CHN				"IP 复用器"

#undef MULT_DEFAULT_DEVICE_LCD_ENG
#define MULT_DEFAULT_DEVICE_LCD_ENG					"      IP Remux"
#undef MULT_DEFAULT_DEVICE_LCD_CHN
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    IP  复用器"

#endif

#define MULT_SERVICE_MAX_NUM							(256)

#endif





#ifdef GM2730S
/*IP <-> ASI*/

#define MULT_SOFT_VERSION							"01.02"
#define MULT_HARD_VERSION							"01.00"
#define MULT_HARD_VERSION_4CE55						"01.10"


#define HWL_CONST_FPGA_FILE_PATH					"/tmp/FPGA2730S.rbf"
#define HWL_CONST_FPGA_FILE_PATH_4CE55				"/tmp/FPGA2730S_4CE55.rbf"

#define MULT_DEVICE_TYPE							(0x27)
#define MULT_DEVICE_SUB_TYPE						(0x31)

#define MULT_DEFAULT_DEVICE_MODEL					"GM-2730S"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"Multifunctional ASI+IP -to-IP Adaptor"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"多功能 ASI+IP-to-IP 适配器"

//LCD行宽为20bytes, 所以注意留出空格让标题显示在中间
#define MULT_DEFAULT_DEVICE_LCD_ENG					" ASI+IP->IP Adaptor "
#define MULT_DEFAULT_DEVICE_LCD_CHN					" ASI+IP->IP 适配器 "

#define MULT_DEVICE_MODUATION_NUM					(0)


#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2730X		

#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			(2048)
#define MULT_FPGA_MAIN_CLK							(62.5)

#define MULT_DEVICE_OLD_HW_INFO_AND_HEAR_BEAT		
#define MULT_DEVICE_NO_TEMP_SENSOR		
#define MULT_USE_ALTERNATE_FPGA_CONFIG
#define SUPPORT_NEW_ALARM_SYSTEM
#define SUPPORT_NIT_DISABLE
#define SUPPORT_INSERTER_DISABLE
#define SUPPORT_BATCH_SERVICE_EDIT
#define MULT_SERVICE_MAX_NUM							(256)

#define SUPPORT_2730_IP_BOARD_4CE55_SUPPORT

#endif



#ifdef GM2730F
/*IP <-> ASI*/

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/FPGA2730S_2730X.rbf"

#define MULT_DEVICE_TYPE							(0x27)
#define MULT_DEVICE_SUB_TYPE						(0x37)

#define MULT_DEFAULT_DEVICE_MODEL					"GM-2730F"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"Serv Manage System"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"节目管理系统"
#define MULT_DEFAULT_DEVICE_LCD_ENG					" Serv Manage System "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    节目管理系统    "

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2730X		

#define MULT_DEVICE_MODUATION_NUM					(0)
#define MULT_DEVICE_ASI_IN_NUM						(0x04)
#define MULT_DEVICE_ASI_OUT_NUM						(0x04)
#define MULT_DEVICE_TUNER_NUM						(0x00)
#define MULT_DEVICE_E3_DS3_NUM						(0x00)
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			(2048)
#define MULT_FPGA_MAIN_CLK							(62.5)

#define MULT_DEVICE_OLD_HW_INFO_AND_HEAR_BEAT		
#define MULT_DEVICE_NO_TEMP_SENSOR		
#define MULT_USE_ALTERNATE_FPGA_CONFIG

#define MULT_ENABLE_ECA_AND_SERVICE_LIST
#define SUPPORT_BSS_SCRAMBLE_SYSTEM
#define MULT_SERVICE_MAX_NUM							(256)

#endif

#ifdef GQ3655
#define MULT_DEVICE_TYPE							0x27
#define MULT_DEVICE_SUB_TYPE				        0x3A

#define MULT_SOFT_VERSION							"01.05"
#define MULT_HARD_VERSION							"02.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3655"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"Multifunctional QAM Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"多功能调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"Multi QAM Modulator"
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    多功能调制器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/main_fpga.rbf"
#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3650DR
#define MULT_DEVICE_MODUATION_NUM					(4)

#define MULT_DEVICE_ASI_IN_NUM						0x16
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048

#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_FPGA_MAIN_CLK							(62.5)

//#define SUPPORT_SYSLOG_MODULE

#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
#define MULT_DEVICE_NO_TEMP_SENSOR
#define MULT_VCO_REF_CLK_USE_25M
//#define MULT_VCO_REF_CLK_USE_10M
#define MULT_SUPPORT_FPGA_ETH
#define SUPPORT_BSS_SCRAMBLE_SYSTEM
#define MULT_SERVICE_MAX_NUM							(256)
#define SUPPORT_NEW_ALARM_SYSTEM

#endif

#ifdef GM2730H
#define MULT_DEVICE_TYPE							0x27
#define MULT_DEVICE_SUB_TYPE				        0x3C

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GM-2730H"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"TS ReMultiplexer"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"TS 复用器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"  TS ReMultiplexer "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"     TS 复用器      "

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2730X		
#define HWL_CONST_FPGA_FILE_PATH					"/tmp/main_fpga.rbf"
#define MULT_DEVICE_MODUATION_NUM					(0)
#define MULT_DEVICE_ASI_IN_NUM						(10)
#define MULT_DEVICE_ASI_OUT_NUM						(2)
#define MULT_DEVICE_TUNER_NUM						(0x00)
#define MULT_DEVICE_E3_DS3_NUM						(0x00)
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			(1000)
#define MULT_FPGA_MAIN_CLK							(62.5)

#define MULT_DEVICE_OLD_HW_INFO_AND_HEAR_BEAT		
#define MULT_DEVICE_NO_TEMP_SENSOR		
#define MULT_USE_ALTERNATE_FPGA_CONFIG

#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
#define MULT_SERVICE_MAX_NUM							(256)

#endif

#ifdef GQ3760A

#define MULT_DEVICE_TYPE							0x1F
#define MULT_DEVICE_SUB_TYPE				        0x02


#define MULT_SOFT_VERSION							"01.04"
#define MULT_HARD_VERSION							"02.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3760A"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"DTMB Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"DTMB  调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"   DTMB Modulator   "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    DTMB  调制器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3760A.rbf"

#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3760A	

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION

//#define MULT_AD9789_USE_CHANNEL_MODE
//#define MULT_SUPPORT_FPGA_ETH

//#define MULT_USE_CHEAP_VCO_REFERENCE		//注意测试模式使用	
#define USE_NEW_QAM_SETTING_FUNCTIONS


//#define MULT_TS_BACKUP_SUPPORT
#define MULT_UNUSED_TS_DISABLE_SUPPORT

#define MULT_TS_BACKUP_OUT_TS_SNUM_USER_ID_OFFSET		1001
#define MULT_SERVICE_MAX_NUM							(256)

#endif

#ifdef GC1818A

#define MULT_DEVICE_TYPE							0x27
#define MULT_DEVICE_SUB_TYPE				        0x19

#define MULT_SOFT_VERSION							"01.06"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3650DR"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"Multifunctional QAM Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"多功能调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"Multi QAM Modulator"
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    多功能调制器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3650DR.rbf"
#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3650DR
#define MULT_DEVICE_MODUATION_NUM					(0)

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048

#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_FPGA_MAIN_CLK							(62.5)

#define MULT_USE_ALTERNATE_FPGA_CONFIG

//#define SUPPORT_SYSLOG_MODULE
#define MULT_SERVICE_MAX_NUM							(256)
#endif



#ifdef GN2000
#define MULT_DEVICE_TYPE							0x20
#define MULT_DEVICE_SUB_TYPE				        0x00

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GN-2000"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"MOSAIC Generator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"马赛克生成器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"MOSAIC Generator"
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    马赛克生成器    "
#define MULT_DEVICE_MODUATION_NUM					(1)

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/main_fpga.rbf"
#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3650DR

#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048

#define MULT_FPGA_MAIN_CLK							(62.5)

//#define SUPPORT_SYSLOG_MODULE
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
#define MULT_DEVICE_NO_TEMP_SENSOR
#define MULT_VCO_REF_CLK_USE_25M
//#define DEBUG_DISABLE_FRP
#define MULT_SERVICE_MAX_NUM							(256)
#endif


#ifdef GM4500
/*IP <-> ASI*/

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/FPGA_2730X2.rbf"

#define MULT_DEVICE_TYPE							(0x27)
#define MULT_DEVICE_SUB_TYPE						(0x44)

#define MULT_DEFAULT_DEVICE_MODEL					"GM-4500"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"Hot Backup Switcher"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"热备份切换器"

#define MULT_DEFAULT_DEVICE_LCD_ENG					"Hot Backup Switcher "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    热备份切换器    "



#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2730X		

#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			(2048)
#define MULT_FPGA_MAIN_CLK							(62.5)

#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
#define MULT_DEVICE_NO_TEMP_SENSOR

#define MULT_TS_BACKUP_SUPPORT
#define MULT_UNUSED_TS_DISABLE_SUPPORT


#define MULT_TS_BACKUP_OUT_TS_SNUM_USER_ID_OFFSET		1001
#define MULT_DEVICE_MODUATION_NUM					(0)

#define MULT_SERVICE_MAX_NUM							(256)
#endif

#ifdef GQ3763 //支持单频网，支持直通单频网中继功能

#define MULT_DEVICE_TYPE							0x1F
#define MULT_DEVICE_SUB_TYPE				        0x02

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3763"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"DTMB Relay"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"DTMB  中继"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"   DTMB Relay   "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    DTMB  中继    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3760B.rbf"
#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3760A	

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
#define MULT_FPGA_MAIN_CLK_SFN						(10)//MHz
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
//#define MULT_AD9789_USE_CHANNEL_MODE
#define MULT_SUPPORT_FPGA_ETH

//#define MULT_USE_CHEAP_VCO_REFERENCE//注意测试模式使用			
#define USE_NEW_QAM_SETTING_FUNCTIONS
#define SUPPORT_SFN_MODULATOR
#define MULT_UNUSED_TS_DISABLE_SUPPORT
#define SUPPORT_NEW_ALARM_SYSTEM
#define SUPPORT_VRS232_MODULE//FPGA 虚拟RS232接口
#define SUPPORT_GNS_MODULE //GPS/BDS 系统支持控制
#define SUPPORT_CLK_ADJ_MODULE//FPGA 10M调整模块
#define SUPPORT_FGPIO_MODULE// FPGA GPIO 功能
#define SUPPORT_MODULATOR_FPGA_TONE
#define SUPPORT_MODULATOR_FREQ_1_HZ
#define SUPPORT_MODULATOR_FREQ_ACCURACY
#define DISABLE_REMUX_MODULE

#define MULT_SERVICE_MAX_NUM							(256)
#endif

#ifdef GM2750 //单频网适配器

#define MULT_DEVICE_TYPE							0x1F
#define MULT_DEVICE_SUB_TYPE				        0x03

#define MULT_SOFT_VERSION							"01.07"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GM-2750"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"SFN Adaptor"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"SFN 适配器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"     SFN Adaptor    "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"     SFN  适配器     "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_2750.rbf"

#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2730X	

#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
#define MULT_FPGA_MAIN_CLK_SFN						(10)

//#define MULT_SUPPORT_FPGA_ETH

#define SUPPORT_SFN_ADAPTER
#define MULT_UNUSED_TS_DISABLE_SUPPORT
#define SUPPORT_NEW_ALARM_SYSTEM
#define SUPPORT_VRS232_MODULE//FPGA 虚拟RS232接口
#define SUPPORT_GNS_MODULE //GPS/BDS 系统支持控制
#define SUPPORT_CLK_ADJ_MODULE//FPGA 10M调整模块
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
#define DISABLE_REMUX_MODULE
#define SUPPORT_REMOTE_COM_CONTROL
#define USE_NEW_QAM_SETTING_FUNCTIONS
#define MULT_SERVICE_MAX_NUM							(256)
#endif

#ifdef LR1800S

#define MULT_DEVICE_TYPE							0x1F
#define MULT_DEVICE_SUB_TYPE				        0x02

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"LR-1800S"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"DTMB IP Transceiver"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"DTMB IP 收发器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"DTMB IP Transceiver "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"  DTMB IP 收发器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3760A.rbf"

#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3760A	

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION

#define SUPPORT_NEW_ALARM_SYSTEM
//#define MULT_USE_CHEAP_VCO_REFERENCE//调试用
#define MULT_SUPPORT_FPGA_ETH
#define USE_NEW_QAM_SETTING_FUNCTIONS
#define DISABLE_SCS_MODULE
#define MULT_SERVICE_MAX_NUM							(256)
#endif



#ifdef GM7000
#define MULT_DEVICE_TYPE							0x29
#define MULT_DEVICE_SUB_TYPE				        0x00

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GM-7000"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"IP Transceiver"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"以太网收发器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"   IP Transceiver   "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    以太网收发器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/gm7000.rbf"
#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3650DR
#define MULT_DEVICE_MODUATION_NUM					(0)

#define MULT_DEVICE_ASI_IN_NUM						0x16
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048

#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_FPGA_MAIN_CLK							(62.5)

//#define SUPPORT_SYSLOG_MODULE

//#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION

#define MULT_DEVICE_NO_TEMP_SENSOR
#define MULT_SUPPORT_FPGA_ETH
#define USE_NEW_QAM_SETTING_FUNCTIONS
#define DISABLE_SCS_MODULE
#define SUPPORT_IP_O_TS_MODULE
#define SUPPORT_NEW_ALARM_SYSTEM
#define MULT_SERVICE_MAX_NUM							(256)
#endif



#ifdef GC1815B

#define MULT_DEVICE_TYPE							0x27
#define MULT_DEVICE_SUB_TYPE				        0x19

#define MULT_SOFT_VERSION							"02.00"
#define MULT_HARD_VERSION							"02.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GC-1815"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"Multi IRD"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"多功能接收机"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"    Multi IRD       "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    多功能接收机    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_1815.rbf"
#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2730X

#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
#define MULT_DEVICE_MODUATION_NUM					(0)


#define MULT_DEVICE_NO_TEMP_SENSOR
#define MULT_USE_ALTERNATE_FPGA_CONFIG
#define DISABLE_SCS_MODULE
#define USE_CI_MODULE
//#define SUPPORT_SYSLOG_MODULE
#define MULT_SERVICE_MAX_NUM							(256)
#endif


#ifdef GC1804C
/* 4 * DTMB/DVBC -> ASI/IP */

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/FPGA1804C.rbf"

#define MULT_DEVICE_TYPE							(0x27)
#define MULT_DEVICE_SUB_TYPE						(0x37)

#define MULT_DEFAULT_DEVICE_MODEL					"GC-1804C"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"DTMB IRD"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"国标地面接收机"

#define MULT_DEFAULT_DEVICE_LCD_ENG					"      DTMB IRD      "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"  国标地面接收机    "



#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2730X		

#define MULT_DEVICE_MODUATION_NUM					(0)
#define MULT_DEVICE_ASI_IN_NUM						(0x04)
#define MULT_DEVICE_ASI_OUT_NUM						(0x04)
#define MULT_DEVICE_TUNER_NUM						(0x00)
#define MULT_DEVICE_E3_DS3_NUM						(0x00)
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			(2048)
#define MULT_FPGA_MAIN_CLK							(62.5)

//#define MULT_DEVICE_OLD_HW_INFO_AND_HEAR_BEAT		
#define MULT_DEVICE_NO_TEMP_SENSOR		
#define SUPPORT_NEW_ALARM_SYSTEM
#define DISABLE_SCS_MODULE
#define MULT_SUPPORT_FPGA_ETH
#define DISABLE_REMUX_MODULE
#define MULT_SERVICE_MAX_NUM							(256)


#endif


#ifdef GQ3760

//#define MULT_QAM_NET_SETTING_USE_VOC_REFERENCE_FREQ_30_24


#define MULT_DEVICE_TYPE							0x1F
#define MULT_DEVICE_SUB_TYPE				        0x01


#define MULT_SOFT_VERSION							"03.00"
#ifdef MULT_QAM_NET_SETTING_USE_VOC_REFERENCE_FREQ_30_24
#define MULT_HARD_VERSION							"03.01 54_3024"
#else
#define MULT_HARD_VERSION							"03.00 54_10"
#endif
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3760"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"DTMB Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"DTMB  调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"   DTMB Modulator   "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    DTMB  调制器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3760.rbf"

#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3760A	

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION

//#define MULT_AD9789_USE_CHANNEL_MODE
//#define MULT_SUPPORT_FPGA_ETH

//#define MULT_USE_CHEAP_VCO_REFERENCE		//注意测试模式使用	
#define USE_NEW_QAM_SETTING_FUNCTIONS
#define SUPPORT_NEW_ALARM_SYSTEM

//#define MULT_TS_BACKUP_SUPPORT
#define MULT_UNUSED_TS_DISABLE_SUPPORT

#define MULT_TS_BACKUP_OUT_TS_SNUM_USER_ID_OFFSET		1001
#define MULT_SERVICE_MAX_NUM							(256)

#endif


#ifdef GQ3760B //支持单频网，但不支持Tuner扩展功能

#define MULT_DEVICE_TYPE							0x1F
#define MULT_DEVICE_SUB_TYPE				        0x02

#define MULT_SOFT_VERSION							"01.05"
#define MULT_HARD_VERSION							"02.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3760B"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"DTMB Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"DTMB  调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"   DTMB Modulator   "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    DTMB  调制器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3760B.rbf"
#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3760A	

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
#define MULT_FPGA_MAIN_CLK_SFN						(10)//MHz
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
//#define MULT_AD9789_USE_CHANNEL_MODE
#define MULT_SUPPORT_FPGA_ETH

//#define MULT_USE_CHEAP_VCO_REFERENCE//注意测试模式使用			
#define USE_NEW_QAM_SETTING_FUNCTIONS
#define SUPPORT_SFN_MODULATOR
#define MULT_UNUSED_TS_DISABLE_SUPPORT
#define SUPPORT_NEW_ALARM_SYSTEM
#define SUPPORT_VRS232_MODULE//FPGA 虚拟RS232接口
#define SUPPORT_GNS_MODULE //GPS/BDS 系统支持控制
#define SUPPORT_CLK_ADJ_MODULE//FPGA 10M调整模块
#define SUPPORT_FGPIO_MODULE// FPGA GPIO 功能
#define SUPPORT_MODULATOR_FPGA_TONE
#define SUPPORT_MODULATOR_FREQ_1_HZ
#define SUPPORT_MODULATOR_FREQ_ACCURACY
#define DISABLE_REMUX_MODULE
#define SUPPORT_ALC
#define SUPPORT_NEW_FRP_MENU_MODULE
//#define USE_MAX287X_2400_40M
#define MULT_SERVICE_MAX_NUM							(256)
#endif

#ifdef GQ3765 //支持单频网，支持DPD，不支持扩展

#define MULT_DEVICE_TYPE							0x1F
#define MULT_DEVICE_SUB_TYPE				        0x04

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3765"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"DTMB Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"DTMB  调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"   DTMB Modulator   "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    DTMB  调制器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3765.rbf"
#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3760A	

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
#define MULT_FPGA_MAIN_CLK_SFN						(10)//MHz
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
//#define MULT_AD9789_USE_CHANNEL_MODE
#define MULT_SUPPORT_FPGA_ETH

//#define MULT_USE_CHEAP_VCO_REFERENCE//注意测试模式使用			
#define USE_NEW_QAM_SETTING_FUNCTIONS
#define SUPPORT_SFN_MODULATOR
#define MULT_UNUSED_TS_DISABLE_SUPPORT
#define SUPPORT_NEW_ALARM_SYSTEM
#define SUPPORT_VRS232_MODULE//FPGA 虚拟RS232接口
#define SUPPORT_GNS_MODULE //GPS/BDS 系统支持控制
#define SUPPORT_CLK_ADJ_MODULE//FPGA 10M调整模块
//#define SUPPORT_FGPIO_MODULE// FPGA GPIO 功能
#define SUPPORT_MODULATOR_FPGA_TONE
#define SUPPORT_MODULATOR_FREQ_1_HZ
#define SUPPORT_MODULATOR_FREQ_ACCURACY
#define DISABLE_REMUX_MODULE
#define SUPPORT_ALC
#define SUPPORT_NTS_DPD_BOARD//芯通的DPD调制板控制模块
#define SUPPORT_NEW_FRP_MENU_MODULE
#define MULT_SERVICE_MAX_NUM							(256)

#endif

#ifdef GQ3768 //支持单频网，支持Tuner

#define MULT_DEVICE_TYPE							0x1F
#define MULT_DEVICE_SUB_TYPE				        0x05

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3768"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"DTMB Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"DTMB  调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"   DTMB Modulator   "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    DTMB  调制器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3768.rbf"
#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3760A	

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
#define MULT_FPGA_MAIN_CLK_SFN						(10)//MHz
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
//#define MULT_AD9789_USE_CHANNEL_MODE

//#define MULT_USE_CHEAP_VCO_REFERENCE//注意测试模式使用			
#define USE_NEW_QAM_SETTING_FUNCTIONS
#define SUPPORT_SFN_MODULATOR
#define MULT_UNUSED_TS_DISABLE_SUPPORT
#define SUPPORT_NEW_ALARM_SYSTEM
//#define SUPPORT_VRS232_MODULE//FPGA 虚拟RS232接口
//#define SUPPORT_GNS_MODULE //GPS/BDS 系统支持控制
#define SUPPORT_CLK_ADJ_MODULE//FPGA 10M调整模块
//#define SUPPORT_FGPIO_MODULE// FPGA GPIO 功能
#define SUPPORT_MODULATOR_FPGA_TONE
#define SUPPORT_MODULATOR_FREQ_1_HZ
#define SUPPORT_MODULATOR_FREQ_ACCURACY
#define DISABLE_REMUX_MODULE
//#define SUPPORT_ALC
#define SUPPORT_REMOTE_COM_CONTROL
#define USE_GGPIO_MODULE
#define MULT_SERVICE_MAX_NUM							(256)
#endif



#ifdef GM8358Q
#define MULT_DEVICE_TYPE							0x27
#define MULT_DEVICE_SUB_TYPE				        0x3F

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GM-8358Q"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"Multifuctional Encoder Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"多功能编码调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"  Encoder Modulator "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"      编码调制器    "

#define HWL_MAIN_FPGA_FILE_PATH						"/tmp/main_board_1858.rbf"
#define HWL_MUX_OUT_FPGA_FILE_PATH					"/tmp/mux_board.rbf"
#define HWL_DVB_C_OUT_FPGA_FILE_PATH				"/tmp/qam_board.rbf"

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3650DR
#define MULT_DEVICE_MODUATION_NUM					(4)

#define MULT_DEVICE_ASI_IN_NUM						0x16
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048

#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_FPGA_MAIN_CLK							(62.5)

//#define SUPPORT_SYSLOG_MODULE

#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
#define MULT_DEVICE_NO_TEMP_SENSOR
#define MULT_VCO_REF_CLK_USE_25M
//#define MULT_VCO_REF_CLK_USE_10M
//#define MULT_SUPPORT_FPGA_ETH
#define SUPPORT_BSS_SCRAMBLE_SYSTEM
//#define MULT_DEVICE_FPGA_CONFIG_IN_AS_MODE

#define SUPPORT_NEW_ALARM_SYSTEM
#define MULT_SERVICE_MAX_NUM							(256)

#endif



#ifdef GN1772
#define MULT_DEVICE_TYPE							0x41
#define MULT_DEVICE_SUB_TYPE				        0x03

#define MULT_SOFT_VERSION							"01.01"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GN-1772"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"Multi-Transcoder"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"多通道转码器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"  Multi-Transcoder  "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    多通道转码器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/mux.rbf"

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2730X
#define MULT_DEVICE_MODUATION_NUM					(0)

#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_SERVICE_MAX_NUM						(512)
#define MULT_FPGA_MAIN_CLK							(62.5)


#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
#define MULT_DEVICE_NO_TEMP_SENSOR
#define SUPPORT_NEW_ALARM_SYSTEM
#define SUPPORT_SYSLOG_MODULE

#define USE_GGPIO_MODULE
#define ENCODER_CARD_PLATFORM						//子板模块的支持！
#define SUPPORT_DRL_MODULE_USE_ETH
#define NEW_FPGA_CONFIG_SYSTEM					//新的主板FPGA配置模块
#define MULT_DEVICE_NO_TEMP_SENSOR
#define SUPPORT_NEW_HWL_MODULE							//使用新的HWL模块，目前仅仅部分协议可用：ETH/Monitor
#define USE_CARD_FRP
#define SUPPORT_PES_ANALYS_FUNCTION
//#define KERNEL_AUTO_UPDATE
#define USE_ZYNQ_AXI_FPGACONFIG_IP
#define SUPPORT_HWL_FPGA_REG_MODULE
#endif


#ifdef ENCODER_CARD_PLATFORM
#define CARD_MODULE_FILE_STORAGE_PATHNAME						"/mnt/baku/modules/"
#define CARD_MODULE_FILE_STORAGE_MOUNT_PORINT_PATHNAME			"/mnt/baku/"
#define CARD_MODULE_FILE_UNFOLD_PATHNAME						"/tmp/"
#define CARD_MODULE_FILE_XML_PATHNAME							MULT_XML_BASE_DIR
#define CARD_MODULE_PARAMETER_XML_FILE							("card_parameter.xml")//这里仅存放子板的参数！
#define CARD_MODULE_INFO_XML_FILE							("card_info.xml")//这里仅存放子板的参数！
#define TRANS_PCR_PID_FUNCTION
#endif

#ifdef GC1804B //单频网适配器

#define MULT_DEVICE_TYPE							0x18
#define MULT_DEVICE_SUB_TYPE				        0x57

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GC-1804B"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"RF -> ASI/IP Adapter"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"RF -> ASI/IP  适配器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"RF -> ASI/IP Adapter"
#define MULT_DEFAULT_DEVICE_LCD_CHN					"RF -> ASI/IP  适配器"

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_1804b.rbf"

#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2730X	

#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)

#define MULT_DEVICE_NO_TEMP_SENSOR
#define MULT_UNUSED_TS_DISABLE_SUPPORT
#define SUPPORT_NEW_ALARM_SYSTEM
#define DISABLE_REMUX_MODULE
#define DISABLE_ROUTE_MODULE
#define MULT_SERVICE_MAX_NUM							(256)
#endif




#ifdef GQ3710B

#define MULT_DEVICE_TYPE							0x27
#define MULT_DEVICE_SUB_TYPE				        0x36/*0x43*/

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GQ-3710B"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"QPSK Modulator"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"QPSK  调制器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"   QPSK Modulator   "
#define MULT_DEFAULT_DEVICE_LCD_CHN					"    QPSK  调制器    "

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_3710B.rbf"

#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_3710A

#define MULT_DEVICE_ASI_IN_NUM						0x08
#define MULT_DEVICE_TUNER_NUM						0x04
#define MULT_DEVICE_E3_DS3_NUM						0x00
#define MULT_DEVICE_USE_QAM_MODULE
#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			2048
#define MULT_FPGA_MAIN_CLK							(62.5)
#define MULT_VCO_REF_CLK_USE_25M
#define MULT_SYSTEM_HAVE_PCR_CORRECT_ADJUST_FUNCTION
#define MULT_SERVICE_MAX_NUM							(256)
#define USE_NEW_QAM_SETTING_FUNCTIONS
#define SUPPORT_NEW_ALARM_SYSTEM
#define DISABLE_SCS_MODULE

#define USE_UNISPI_DRIVER
#define USE_MAX2871
#endif




#ifdef GN1866 

#define MULT_DEVICE_TYPE							0x27
#define MULT_DEVICE_SUB_TYPE				        0x41

#define MULT_SOFT_VERSION							"01.00"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GN-1866"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"HEVC/H.265HD Encoder"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"HEVC/H.265高清编码器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"HEVC/H.265HD Encoder"
#define MULT_DEFAULT_DEVICE_LCD_CHN					"HEVC/H.265高清编码器"

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/fpga_none.rbf"

#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_2730X	

#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			64
#define MULT_FPGA_MAIN_CLK							(62.5)

#define MULT_DEVICE_NO_TEMP_SENSOR
#define MULT_UNUSED_TS_DISABLE_SUPPORT
#define SUPPORT_NEW_ALARM_SYSTEM
//#define DISABLE_REMUX_MODULE
#define DISABLE_ROUTE_MODULE
#define MULT_SERVICE_MAX_NUM							(256)
#endif

#ifdef GN1846 

#include <sys/syscall.h>  
#define GLOBAL_GETTID() (long int)syscall(__NR_gettid)  

/* 打印颜色定义*/
#define ANSI_COLOR_NONE "\033[0m"
#define ANSI_COLOR_RED "\033[0;31m"
#define ANSI_COLOR_LIGHT_RED "\033[1;31m"
#define ANSI_COLOR_GREEN "\033[0;32m"
#define ANSI_COLOR_LIGHT_GREEN "\033[1;32m"
#define ANSI_COLOR_BLUE "\033[0;34m"
#define ANSI_COLOR_LIGHT_BLUE "\033[1;34m"
#define ANSI_COLOR_DARY_GRAY "\033[1;30m"
#define ANSI_COLOR_CYAN "\033[0;36m"
#define ANSI_COLOR_LIGHT_CYAN "\033[1;36m"
#define ANSI_COLOR_PURPLE "\033[0;35m"
#define ANSI_COLOR_LIGHT_PURPLE "\033[1;35m"
#define ANSI_COLOR_BROWN "\033[0;33m"
#define ANSI_COLOR_YELLOW "\033[1;33m"
#define ANSI_COLOR_LIGHT_GRAY "\033[0;37m"
#define ANSI_COLOR_WHITE "\033[1;37m"

/* 带名称打印，方便调试 */
#define GLOBAL_NAMED_TRACE(a, conversion) GLOBAL_TRACE((#a" = %"#conversion"\n", (a))) 

#define MULT_DEVICE_TYPE							0x41
#define MULT_DEVICE_SUB_TYPE				        0x07

#define MULT_SOFT_VERSION							"02.01T"
#define MULT_HARD_VERSION							"01.00"
#define MULT_DEFAULT_DEVICE_MODEL					"GN-1846"
#define MULT_DEFAULT_DEVICE_NAME_ENG				"H.264HD Encoder"
#define MULT_DEFAULT_DEVICE_NAME_CHN				"H.264高清编码器"
#define MULT_DEFAULT_DEVICE_LCD_ENG					"H.264HD Encoder"
#define MULT_DEFAULT_DEVICE_LCD_CHN					"H.264高清编码器"

#define HWL_CONST_FPGA_FILE_PATH					"/tmp/i2s_8mux1.rbf"

#define MULT_DEVICE_MODUATION_NUM					(1)

#define MULT_DEVICE_SIMU_TYPE						HWL_DEVICE_SIMU_1846	

#define MULT_HARDWARE_INSERTER_SLOT_NUMBER			64
#define MULT_FPGA_MAIN_CLK							(62.5)

#define MULT_MAX_CHN_NUM							(4)

//#define MULT_DEVICE_NO_TEMP_SENSOR
#define MULT_UNUSED_TS_DISABLE_SUPPORT
#define SUPPORT_NEW_ALARM_SYSTEM
//#define DISABLE_REMUX_MODULE
#define DISABLE_ROUTE_MODULE
#define MULT_SERVICE_MAX_NUM							(256)
#define DISABLE_SCS_MODULE
#define USE_CARD_FRP

#endif



#endif

//eof

